### ISSUE TITLE
Make It Seo Friendly

### ISSUE THREAD

**Issue by karantec** [karantec/Planner#11]
Analyze the website and make it Seo Friendly.

**Comment by karantec** [comment]
Yes, I can do it.  Work on it

**Comment by karantec** [comment]
Work on it

**Comment by Diwanshumidha** [comment]
Can you assign this issue to me

**Comment by karantec** [comment]
fork and clone and work on  it

**Comment by Diwanshumidha** [comment]
https://planner-alpha.vercel.app/events?category=3 
These links are not present causing Broken Links
so should i comment these or leave it as it is

**Comment by Diwanshumidha** [comment]
I have opened a pr

**Comment by Diwanshumidha** [comment]
@karantec 
https://planner-alpha.vercel.app/events?category=3
These links are not present causing Broken Links
so should i comment these or leave it as it is

apart from this i have fixed SEO

**Comment by Diwanshumidha** [comment]
@karantec Is there any problem

**Comment by karantec** [comment]
If you can find any bug , you can make it pr and done the changes.

 I will accept the pr

**Comment by Diwanshumidha** [comment]
@karantec I have opened a PR #14
